services:
  - type: web
    name: football-selector
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: API_FOOTBALL_KEY
        sync: false
